MONGOHOST: "arctrdcn018.rs.gsu.edu"
DBNAME: "babywire_ageExperiment"
SWAP_CAP: 10000

# Change if you know what you're doing
SAMPLE: ["data", "label"]
WRITE_COLLECTION: "write"
READ_COLLECTION: "read"
COUNTER_COLLECTION: "counter"
TEMP_COLLECTION: "temp"
CHUNKSIZE: 10
